### ISSUE TITLE
BCF

### ISSUE THREAD

**Issue by moonso** [dnil/rhocall#1]
Hi,

is it important that the tool can handle BCF-files?
I was thinking that it would be nice to skip cyvcf2 to reduce dependency problems...

Otherwise I am working on making a proper python package of your tool.

What do you think?

Måns

**Comment by dnil** [comment]
So far, Ive got a mix of VCF and BCF to work with on the patients, so pretty convenient. But one could always just convert to VCF first. Which parser would you suggest? Pyvcf?

I'll try to find a few h to adopt output to VCF as well; the idea being to use genmod inheritance markup, if available, to improve UPD vs IBD calls and anyway mark variants in the VCF with size and type of homozygous block they are in.

**Comment by moonso** [comment]
Ok. If you could accept .vcf and .vcf.gz I would prefer to not use any parser at all 😺 
No but really, thas is my experience, does not matter how good any parser is, there will allways show up new problems with VCF files...
Since you are not retreiving to much information from the file I have parsed myself in my branch.
But maybe you have other plans for the future?
Would be easier if we could meet and discuss

**Comment by dnil** [comment]
That works for me for the moment; I take it you have a robust way of getting to the genmod calls as well. :)

Nah, in the pipe was family info - but let’s use genmod for now. Also next including bcftools probabilistic calls, but that doesn’t need any internal vcf/bcf-parsing.

Is your branch local-only, or did you put it up somewhere?

I might pop by Wednesday for the SCOUT-meeting; otherwise Thursday at clinical?

Cheers!

**Comment by moonso** [comment]
Sounds good! I haven't pushed my changes yet but ping you when done.
See you later this week then

**Comment by dnil** [comment]
Closed by #2!
